apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fooclusters.example.tech
spec:
  group: example.tech
  names:
    kind: FooCluster
    listKind: FooClusterList
    plural: fooclusters
    shortNames:
    - foo
    singular: foocluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        required:
        - spec
        type: object
        properties:
          spec:
            type: object
            properties:
              bar:
                type: string
                nullable: true
                default: "defaultvalue"